### ISSUE TITLE
region="custom" not set in mCSEATest

### ISSUE THREAD

**Issue by MatthiasLienhard** [jordimartorell/mCSEA#1]
When running mCSEATest with customAnnotation, the "region" variable is not set, so the previous result is overwritten or, if regionsTypes= NULL, the function results in Error:
Error in .performGSEA(region, rank, platform, customAnnotation, minCpGs,  : 
  object 'region' not found

**Comment by jordimartorell** [comment]
Hi @MatthiasLienhard 

Thank you very much for reporting this problem. I fixed it in version 1.0.1, which will be available in the next few days in Bioconductor. You can also install the github version, which is already fixed.

Thanks again!
Jordi
