### ISSUE TITLE
Wrong threshold is applied for minimum p-value in .integrateCore function within mCSEAIntegrate 

### ISSUE THREAD

**Issue by nievergeltlab** [jordimartorell/mCSEA#2]
This function kept failing when I tried to force it to plot genes with low correlations to expression.

If you look at line 252 of mCSEAIntegrate, it says,

          if (corResult[["p.value"]] < minCor &

But this comparison should be the minimum P value threshold, rather than the minimum correlation. i.e. it should be

if (corResult[["p.value"]] < minP

**Comment by jordimartorell** [comment]
Hi @nievergeltlab 

Thank you very much for your feedback, it seems that you are right. I am going to fix this issue right now.

**Comment by jordimartorell** [comment]
Fixed in both devel and release versions of Bioconductor. You can update now the package to version 1.2.2 (release) or 1.3.4 (devel).

Thanks again, I will close this issue now.
