### ISSUE TITLE
Missing expression or methylation values will cause mCSEAIntegrate to be unable to plot

### ISSUE THREAD

**Issue by nievergeltlab** [jordimartorell/mCSEA#3]
I encountered this error: "Error in plot.window(...) : need finite 'ylim' values"

This occured when I had a methylation site with some missing data. This is because the plot axes are determined by a min/max function, which takes column mean values as an input. The default behavior of the column means function is to give an "NA" if there is missing data. So given missing methylation data, these means functions return NA. The NA is then passed to the min/max functions, which in turn return NA. Then the plot axes are set to NA, resulting in the error.

I suggest making the following simple edit to ignore NA values for calculation of axis limits:

    meth1 <- colMeans(methData[corCpGs, pheno == levels(pheno)[1]],na.rm=T)
    meth2 <- colMeans(methData[corCpGs, pheno == levels(pheno)[2]],na.rm=T)

           expr1 <- colMeans(exprData[gene, pheno == levels(pheno)[1]],na.rm=T)
            expr2 <- colMeans(exprData[gene, pheno == levels(pheno)[2]],na.rm=T)

**Comment by jordimartorell** [comment]
Hi @nievergeltlab 

Thank you again for noticing this issue, I am going to fix it. In a few days, a new version of the package should be available.

**Comment by jordimartorell** [comment]
Fixed in both devel and release versions of Bioconductor. You can update now the package to version 1.2.2 (release) or 1.3.4 (devel).

Thanks again, I will close this issue now.
